KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
TOPIC_NAME: "traffic-volume"
TOPIC_AGGREGATED: "traffic-aggregated"
TOPIC_FORECAST: "traffic-forecast"
REDIS_PORT: 6379
REDIS_HOST: "localhost"
NUM_WORKERS: 4
FPS_LIMIT: 1
cameras:
  - camera_id: cam_000
    location: Chuong_Trinh
    source: videos/chuong_trinh.mp4

  - camera_id: cam_001
    location: Le_Trong_Tan
    source: videos/13-10-LeTrongTan.mp4
